// End-to-end build generator.
//
// For a given class, profile, and (optionally) skill, assemble a complete
// ParsedBuild — weapon + supports + tree allocation — and return it along
// with its composeDamage score. The output is constrained to be in-game
// reproducible:
//   - Weapon base + mods generated by generateWeapon (Layer 1-validated)
//   - Skill + supports drawn from skills.json (Layer 2-3-validated)
//   - Tree borrowed from a known-good fixture (Layer 4-validated)
//
// v1 SCOPE:
//   - Single class supported: Huntress
//   - Tree allocation TEMPLATED from zeolet's baseline (130 nodes, lvl 97)
//   - Slots filled: Weapon 1 (generated). Other slots use zeolet's items.
//   - Skill candidates: bow-attack skills
//   - Supports: greedily picked via optimizeSupports
//
// v1 deliberately does NOT generate non-weapon gear (we don't have armour
// /jewellery base data yet — only weapons). All other slots are taken
// from zeolet's build as a template — the "best non-weapon gear for an
// Amazon bow build" question is for a later iteration.

import { ParsedBuild, ParsedItem } from '../validation/types';
import { composeDamage } from '../damage-v2/composeDamage';
import { validateBuild, ValidationResult } from '../validation';
import { candidateSkills } from './candidateSkills';
import { generateWeaponForSkill } from './generateWeapon';
import { pickUniqueWeaponsForSkill, pickUniquesForSlot } from './generateUniqueWeapons';
import { generateRareForSlot } from './generateRareArmour';
import { optimizeSupports } from '../optimizer/optimizeSupports';
import { synthesizeTree, TreeStrategy, ScalingBias } from './synthesizeTree';

import skillsJson from '../data/generated/skills.json';
import weaponBasesJson from '../data/generated/weapon-bases.json';
import zeoletTemplate from '../data/baseline-builds/zeolet-build.json';

interface SkillRecord {
  id: string;
  name: string;
  isSupport: boolean;
  skillTypes: string[];
  weaponTypes: string[];
  requireSkillTypes: string[];
  excludeSkillTypes: string[];
  gemFamily: string[];
}

const skillsById: Record<string, SkillRecord> = {};
const allSupports: SkillRecord[] = [];
for (const s of skillsJson as SkillRecord[]) {
  skillsById[s.id] = s;
  if (s.isSupport) allSupports.push(s);
}

interface WeaponBase {
  id: string;
  type: string;
  tags: string[];
}
const weaponBasesByName: Record<string, WeaponBase> = {};
for (const b of weaponBasesJson as WeaponBase[]) weaponBasesByName[b.id] = b;

/**
 * Per-class hand-picked ascendancy + non-weapon-gear strategy. Today we
 * only model:
 *   - which ascendancy this generator targets (only one per class for v1)
 *   - whether the class typically wields a two-handed weapon (so we know
 *     to drop the offhand slot when generating)
 */
/**
 * Per-character-level constraints. PoE2 endgame is gated by:
 *   - passive points: ~1/level from level 2 + ~24 quest grants
 *   - active gem level: requirement scales with character level
 *     (lvl 21 gems need char ~79; lvl 23 needs char ~84)
 *   - item level: practical drops cap at the area you can clear
 *
 * The user can override any of these via explicit options; the defaults
 * below give "what the build looks like at this leveling milestone".
 */
export interface LevelProfile {
  passivePoints: number;
  gemLevel: number;
  itemLevel: number;
}
export const LEVEL_PROFILES: Record<number, LevelProfile> = {
  30:  { passivePoints: 35,  gemLevel: 9,  itemLevel: 33 }, // mid-campaign (Act 2-3)
  50:  { passivePoints: 72,  gemLevel: 15, itemLevel: 55 },
  65:  { passivePoints: 87,  gemLevel: 17, itemLevel: 65 }, // mid-campaign → early maps
  84:  { passivePoints: 106, gemLevel: 20, itemLevel: 78 },
  90:  { passivePoints: 112, gemLevel: 21, itemLevel: 82 },
  100: { passivePoints: 122, gemLevel: 23, itemLevel: 82 },
};

/**
 * Per-class metadata. `ascendancy` is the default we pick if the caller
 * doesn't override; `preferTwoHand` tells the generator to drop the
 * offhand slot. `archetype` selects the candidate-skill filter — attacks
 * (constrained to a weapon family) versus spells.
 *
 * All 9 PoE2 classes are listed. `ascendancies` is the full set the user
 * can pick from in the UI; `defaultAscendancy` is the starting choice.
 */
export interface ClassProfile {
  defaultAscendancy: string;
  ascendancies: string[];
  preferTwoHand: boolean;
  archetype: 'bow-attack' | 'crossbow-attack' | 'mace-attack' | 'staff-attack' | 'spell' | 'shapeshift-totem';
}
export const CLASS_PROFILE: Record<string, ClassProfile> = {
  // Spirit Walker (Huntress) and Martial Artist (Monk) are the two new 0.5
  // ascendancies. Listed here so the generator can target them; the
  // synthesizer no-ops on them until the composer's passive-tree.json is
  // refreshed from PoB-PoE2's 0.5 data (`npm run sync-data`).
  Huntress:  { defaultAscendancy: 'Amazon',          ascendancies: ['Amazon', 'Ritualist', 'Spirit Walker'],             preferTwoHand: false, archetype: 'bow-attack'      },
  Ranger:    { defaultAscendancy: 'Deadeye',         ascendancies: ['Deadeye', 'Pathfinder'],                            preferTwoHand: false, archetype: 'bow-attack'      },
  Warrior:   { defaultAscendancy: 'Titan',           ascendancies: ['Titan', 'Warbringer', 'Smith of Kitava'],           preferTwoHand: true,  archetype: 'mace-attack'     },
  Mercenary: { defaultAscendancy: 'Witchhunter',     ascendancies: ['Witchhunter', 'Tactician', 'Gemling Legionnaire'],  preferTwoHand: true,  archetype: 'crossbow-attack' },
  Monk:      { defaultAscendancy: 'Invoker',         ascendancies: ['Invoker', 'Acolyte of Chayula', 'Martial Artist'],  preferTwoHand: true,  archetype: 'staff-attack'    },
  Druid:     { defaultAscendancy: 'Shaman',          ascendancies: ['Shaman', 'Oracle'],                                 preferTwoHand: true,  archetype: 'shapeshift-totem'},
  Witch:     { defaultAscendancy: 'Blood Mage',      ascendancies: ['Blood Mage', 'Infernalist', 'Lich'],                preferTwoHand: false, archetype: 'spell'           },
  Sorceress: { defaultAscendancy: 'Stormweaver',     ascendancies: ['Stormweaver', 'Chronomancer', 'Disciple of Varashta'], preferTwoHand: false, archetype: 'spell'        },
};

/**
 * Load the fixture we use as a tree/gear template. We pick zeolet's
 * Huntress build because it's the only Huntress baseline we have, and
 * its tree (130 nodes from the Huntress class start) is a known-good
 * allocation reachable from the class start.
 */
function loadTemplateBuild(): ParsedBuild {
  // Deep-clone via JSON round-trip so callers can mutate freely without
  // poisoning the bundled template.
  return JSON.parse(JSON.stringify(zeoletTemplate)) as ParsedBuild;
}

export interface GeneratedBuild {
  skillId: string;
  skillName: string;
  weaponBase: string;
  /** "RARE" if the picker generated affixes; "UNIQUE" if it chose a real
   *  unique item from the database. */
  weaponRarity: 'RARE' | 'UNIQUE';
  /** The unique item's name when weaponRarity === 'UNIQUE', else null. */
  weaponUniqueName: string | null;
  /** The exact ItemMod IDs the generator chose for the weapon (RARE only;
   *  uniques have fixed mods that don't come from item-mods.json). */
  weaponModIds: string[];
  /** How the skill is delivered. For spell skills the generator picks the
   *  higher-scoring of direct vs cast_on_crit modes. */
  triggerMode: 'direct' | 'cast_on_crit';
  /** Level profile this build was generated against. */
  characterLevel: number;
  gemLevel: number;
  passivePoints: number;
  itemLevel: number;
  build: ParsedBuild;
  dps: number;
  validation: ValidationResult;
  notes: string[];
}

/**
 * Generate a fully-specified build around a single skill.
 *
 * Strategy:
 *   1. Generate the highest-damage Layer-1-valid weapon for the skill.
 *   2. Seed the build with the class template (zeolet) — keeps tree +
 *      non-weapon gear known-valid.
 *   3. Swap in the generated weapon and the chosen skill (replace the
 *      template's mainActiveSkill group's primary gem).
 *   4. Seed with neutral supports (5 universally-compatible ones), then
 *      run optimizeSupports to greedily upgrade each slot.
 *   5. Compose + validate.
 */
export function generateBuildForSkill(
  className: string,
  skillId: string,
  options: {
    itemLevel?: number;
    /** Character level (50 / 84 / 90 / 100). Looks up gem level, passive
     *  points, and item level defaults from LEVEL_PROFILES. Individual
     *  knobs (itemLevel / gemLevel / passivePoints) override the profile. */
    characterLevel?: number;
    gemLevel?: number;
    passivePoints?: number;
    /** Override the class's default ascendancy (must be one listed in
     *  CLASS_PROFILE[className].ascendancies). */
    ascendancy?: string;
    supportOptimizationPasses?: number;
  } = {},
): GeneratedBuild | null {
  const charLevel = options.characterLevel ?? 100;
  const profile = LEVEL_PROFILES[charLevel] ?? LEVEL_PROFILES[100];
  const itemLevel = options.itemLevel ?? profile.itemLevel;
  const gemLevel = options.gemLevel ?? profile.gemLevel;
  const passivePoints = options.passivePoints ?? profile.passivePoints;
  const classProfile = CLASS_PROFILE[className];
  if (!classProfile) {
    throw new Error(`Generator doesn't know how to handle class "${className}". Add an entry to CLASS_PROFILE.`);
  }
  const ascendancy = options.ascendancy && classProfile.ascendancies.includes(options.ascendancy)
    ? options.ascendancy
    : classProfile.defaultAscendancy;
  const skill = skillsById[skillId];
  if (!skill || skill.isSupport) return null;

  const notes: string[] = [
    `character level ${charLevel}: gemLv ${gemLevel}, ${passivePoints} passive points, ilvl ${itemLevel}`,
    'v1 generator: non-weapon gear templated from zeolet baseline (provides global stats only)',
    'v1 generator: tree allocation synthesized via BFS-greedy from class start',
    'v1 generator: no uniques (we have not extracted Uniques/*.lua yet)',
  ];

  // Step 1 — generate the RARE-tier weapon baseline
  const rareWeaponOut = generateWeaponForSkill(skillId, itemLevel);
  if (!rareWeaponOut) return null;

  // Step 1b — collect candidate UNIQUE weapons for this skill. We'll score
  // each and use whichever option (rare or unique) yields higher DPS.
  const uniqueCandidates = pickUniqueWeaponsForSkill(skillId);

  // Step 2 — clone template; deep-enough copy for our mutations.
  const template = loadTemplateBuild();
  const build: ParsedBuild = {
    ...template,
    equipped: { ...template.equipped },
    skillGroups: template.skillGroups.map(g => ({ ...g, gems: g.gems.slice() })),
  };

  // Step 3 — choose the best weapon among (rare-generated, each unique).
  // The composer is the arbiter: equip each candidate, compose, pick max.
  // For efficiency we equip-and-test before the support-optimization pass,
  // so the chosen weapon then carries through the rest of the build.
  type WeaponPick = {
    item: typeof rareWeaponOut.item;
    rarity: 'RARE' | 'UNIQUE';
    uniqueName: string | null;
    modIds: string[];
    score: number;
  };
  const weaponCandidates: WeaponPick[] = [];
  // Tentative skill-group setup so composeDamage can score below.
  // We'll redo this properly after the weapon decision.
  const tplGroup = build.skillGroups.find(g => g.gems.some(x => x.skillId === 'IceShotPlayer'))!;
  const tplGroupIdx = build.skillGroups.indexOf(tplGroup);
  const seedSupportsScout = tplGroup.gems.filter(g => g.skillId && skillsById[g.skillId] && skillsById[g.skillId].isSupport);
  build.skillGroups[tplGroupIdx] = {
    ...tplGroup,
    gems: [
      { skillId: skill.id, nameSpec: skill.name, variantId: null, gemId: null, level: gemLevel, quality: 23, enabled: true },
      ...seedSupportsScout,
    ],
  };

  // `rareWeaponOut` is non-null here (early-return above guarantees it).
  type RareItem = NonNullable<typeof rareWeaponOut>['item'];
  function scoreWith(item: RareItem): number {
    build.equipped['Weapon 1'] = item;
    try {
      return composeDamage({ build, skillGroupIndex: tplGroupIdx, skillId: skill.id }).dps;
    } catch { return 0; }
  }

  weaponCandidates.push({
    item: rareWeaponOut.item, rarity: 'RARE', uniqueName: null,
    modIds: rareWeaponOut.mods.map(m => m.id), score: scoreWith(rareWeaponOut.item),
  });
  for (const uc of uniqueCandidates) {
    weaponCandidates.push({
      item: uc.item, rarity: 'UNIQUE', uniqueName: uc.uniqueName,
      modIds: [], score: scoreWith(uc.item),
    });
  }
  weaponCandidates.sort((a, b) => b.score - a.score);
  const bestWeapon = weaponCandidates[0];
  build.equipped['Weapon 1'] = bestWeapon.item;
  if (bestWeapon.rarity === 'UNIQUE') {
    notes.push(`unique weapon chosen: "${bestWeapon.uniqueName}" (scored ${bestWeapon.score.toFixed(0)} vs best rare ${weaponCandidates.find(c => c.rarity === 'RARE')?.score.toFixed(0)})`);
  }

  const weaponBase = weaponBasesByName[bestWeapon.item.base ?? ''];
  const isTwoHandedWeapon = weaponBase
    ? weaponBase.tags.includes('twohand') || weaponBase.tags.includes('two_hand_weapon')
    : false;
  if (isTwoHandedWeapon || classProfile.preferTwoHand) {
    // 2H weapons occupy both weapon slots; remove the offhand if the
    // template had one (e.g. zeolet's quiver Rage Skewer).
    delete build.equipped['Weapon 2'];
    notes.push('weapon is two-handed; offhand slot removed');
  }
  // Set the build's class so synthesizeTree / validator see the right context.
  build.build.className = className;
  build.build.ascendClassName = ascendancy;

  // For non-channelled spell skills, add Archmage as a reservation buff in
  // its own group. Archmage grants 4% damage as extra lightning per 100 max
  // mana to non-channelled spells — a build-defining mechanic for mana
  // stackers (Witch / Sorceress). The composer's active-skill-buffs pass
  // picks it up from any group on the build.
  const isSpellSkill = skill.skillTypes.includes('Spell') && !skill.skillTypes.includes('Attack');
  const isChannelled = skill.skillTypes.includes('Channel') || skill.skillTypes.includes('Channelled');
  if (isSpellSkill && !isChannelled) {
    // Witch / Sorceress staples for sustained boss-DPS scenarios:
    //   - Archmage (gain-as-lightning per 100 mana, the build-defining buff)
    //   - Voltaic Mark (35% increased damage when target electrocuted)
    // Freezing Mark and Sniper's Mark are already in the zeolet template
    // we inherit from, so they don't need to be added explicitly.
    build.skillGroups = [
      ...build.skillGroups,
      {
        label: 'Archmage Reservation',
        slot: null,
        useSecondWeaponSet: false,
        gems: [
          { skillId: 'ArchmagePlayer', nameSpec: 'Archmage', variantId: null, gemId: null, level: gemLevel, quality: 20, enabled: true },
        ],
      } as any,
      {
        label: 'Voltaic Mark',
        slot: null,
        useSecondWeaponSet: false,
        gems: [
          { skillId: 'VoltaicMarkPlayer', nameSpec: 'Voltaic Mark', variantId: null, gemId: null, level: gemLevel, quality: 20, enabled: true },
        ],
      } as any,
    ];
    notes.push('added Archmage + Voltaic Mark to spell build');
  }

  // Synthesise a class-appropriate tree using BOTH strategies and pick the
  // one whose composed DPS is higher. Each has cases where it dominates
  // (greedy: dense-start classes like Warrior; Steiner: spread-out trees
  // like Huntress) and our nodeScore heuristic can't reliably predict which
  // wins — only the composer can.
  //
  // For non-channelled spell builds we also anchor Eldritch Battery (tree
  // node 57513). It converts gear-ES into mana → fuels Archmage's
  // gain-as-lightning. Without forcing it, the heuristic scorer misses it.
  const requiredTreeNodes: number[] = [];
  if (isSpellSkill && !isChannelled) requiredTreeNodes.push(57513); // Eldritch Battery
  // Two axes explored together: ALLOCATION strategy (greedy/steiner) × SCALING
  // bias (balanced/crit/ailment). The bias makes the tree COMMIT to an
  // archetype so crit/ailment builds can cross their pay-off threshold; the
  // composer ranks all combos and the winner is kept. This is the discovery
  // engine: a committed crit tree can beat the generic one, surfacing a build
  // the generator would otherwise never assemble.
  const strategies: TreeStrategy[] = ['greedy', 'steiner'];
  // Armour-as-damage is a COMMITTED archetype that only pays off with Smith of
  // Kitava's massive armour scaling (+200/notable, +100% armour→chaos). On any
  // other chassis the general-tree armour-applies nodes (+30%) just bolt a big
  // flat onto a damage build and spuriously win — so only offer the armour bias
  // where Smith is available. Other classes don't get an armour variant.
  const hasSmith = classProfile.ascendancies.includes('Smith of Kitava');
  const biases: ScalingBias[] = hasSmith
    ? ['balanced', 'crit', 'ailment', 'armour']
    : ['balanced', 'crit', 'ailment'];
  // Some biases prefer a different ascendancy than the class default: the
  // armour-as-damage payoff lives in Smith of Kitava (Warrior). Route the
  // armour variant there if the class can take it; otherwise stay on default.
  const ascForBias = (bias: ScalingBias): string =>
    bias === 'armour' && classProfile.ascendancies.includes('Smith of Kitava')
      ? 'Smith of Kitava'
      : ascendancy;
  let bestTreeDps = -Infinity;
  let bestStrategy: TreeStrategy = 'greedy';
  let bestBias: ScalingBias = 'balanced';
  let bestAscendancy = ascendancy;
  for (const strat of strategies) {
    for (const bias of biases) {
      const asc = ascForBias(bias);
      const synth = synthesizeTree(className, { skillTypes: skill.skillTypes }, passivePoints, asc, strat, requiredTreeNodes, bias);
      if (!synth) continue;
      build.trees = [{
        classId: synth.classId,
        classInternalId: synth.classInternalId,
        ascendClassId: null,
        ascendancyInternalId: synth.ascendancyInternalId,
        treeVersion: synth.treeVersion,
        nodes: synth.nodes,
        masteryEffects: '',
      }];
      try {
        const score = composeDamage({ build, skillGroupIndex: tplGroupIdx, skillId: skill.id }).dps;
        if (score > bestTreeDps) {
          bestTreeDps = score;
          bestStrategy = strat;
          bestBias = bias;
          bestAscendancy = asc;
        }
      } catch { /* skip combo on failure */ }
    }
  }
  // Re-synthesise the winning (strategy, bias, ascendancy) as the final tree.
  const synth = synthesizeTree(className, { skillTypes: skill.skillTypes }, passivePoints, bestAscendancy, bestStrategy, requiredTreeNodes, bestBias);
  build.build.ascendClassName = bestAscendancy;
  if (synth) {
    build.trees = [{
      classId: synth.classId,
      classInternalId: synth.classInternalId,
      ascendClassId: null,
      ascendancyInternalId: synth.ascendancyInternalId,
      treeVersion: synth.treeVersion,
      nodes: synth.nodes,
      masteryEffects: '',
    }];
    notes.push(`synthesized tree (${bestStrategy}, ${bestBias} bias): ${synth.nodes.length} nodes from ${className} class start`);
  } else {
    notes.push(`WARNING: tree synthesis failed for ${className}; falling back to template tree`);
  }

  // Step 4 — skill group is already seeded above for weapon scoring.
  const mainIdx = tplGroupIdx;

  // Step 4b — score each non-weapon slot's options and pick the highest:
  //   1. CURRENT (template from zeolet baseline)
  //   2. RARE  (generated for this class + skill via armour-bases + item-mods)
  //   3. UNIQUE (each viable unique for that slot)
  // We hold the rest of the build constant per evaluation.
  const NON_WEAPON_SLOTS = ['Helmet','Body Armour','Gloves','Boots','Belt','Amulet','Ring 1','Ring 2','Weapon 2'];
  const slotPicks: { slot: string; from: string; to: string; type: 'RARE' | 'UNIQUE' }[] = [];
  for (const slot of NON_WEAPON_SLOTS) {
    const current = build.equipped[slot];
    const candidates: { label: string; type: 'TEMPLATE' | 'RARE' | 'UNIQUE'; item: ParsedItem | undefined }[] = [];
    if (current) candidates.push({ label: current.name || current.base || '?', type: 'TEMPLATE', item: current });

    // Rare candidate generated for this class + skill (only meaningful for
    // body/helmet/gloves/boots/belt/amulet/ring slots that armour-bases.json
    // covers; not Weapon 2 which is offhand-specific).
    if (slot !== 'Weapon 2') {
      // Offer BOTH a balanced rare and a bias-committed rare; the best-DPS
      // slot eval below keeps whichever wins, so bias gear can only ever help
      // (a crit rare wins only when the tree supplies enough crit chance to
      // make crit damage bonus pay — otherwise the balanced rare wins).
      const rareBalanced = generateRareForSlot(slot, className, skill.id, itemLevel, 'balanced');
      if (rareBalanced) candidates.push({ label: `Generated Rare (${rareBalanced.base.id})`, type: 'RARE', item: rareBalanced.item });
      if (bestBias !== 'balanced') {
        const rareBias = generateRareForSlot(slot, className, skill.id, itemLevel, bestBias);
        if (rareBias) candidates.push({ label: `Generated Rare ${bestBias} (${rareBias.base.id})`, type: 'RARE', item: rareBias.item });
      }
    }

    // Uniques eligible for this slot. EXCLUDE armour-as-damage uniques
    // (Doryani's Prototype etc.) unless the build is armour-committed — their
    // "% of Armour applies to Damage" otherwise bolts a huge type-mismatched
    // flat onto any build via the compose-driven slot eval, ballooning DPS.
    for (const u of pickUniquesForSlot(slot)) {
      const isArmourDmgUnique = [...u.item.implicits, ...u.item.explicits]
        .some(l => /of Armour also applies to .* Damage/i.test(l));
      if (isArmourDmgUnique && bestBias !== 'armour') continue;
      candidates.push({ label: u.uniqueName, type: 'UNIQUE', item: u.item });
    }
    if (candidates.length === 0) continue;

    let bestDps = -Infinity;
    let bestIdx = 0;
    for (let i = 0; i < candidates.length; i++) {
      const c = candidates[i];
      if (!c.item) continue;
      build.equipped[slot] = c.item;
      try {
        const score = composeDamage({ build, skillGroupIndex: tplGroupIdx, skillId: skill.id }).dps;
        if (score > bestDps) { bestDps = score; bestIdx = i; }
      } catch { /* skip on failure */ }
    }
    const picked = candidates[bestIdx];
    if (picked.item) build.equipped[slot] = picked.item;
    if (picked.type !== 'TEMPLATE' && current) {
      slotPicks.push({
        slot,
        from: current.name || current.base || '?',
        to: picked.label,
        type: picked.type as 'RARE' | 'UNIQUE',
      });
    }
  }
  if (slotPicks.length > 0) {
    notes.push(`slot upgrades: ${slotPicks.map(p => `${p.slot} "${p.from}" → "${p.to}" [${p.type}]`).join('; ')}`);
  }

  // Step 5 — greedy support optimisation (single-pass via optimizeSupports;
  // we apply the top swap per slot then refresh).
  const passes = options.supportOptimizationPasses ?? 3;
  // High-confidence threshold: a swap whose improvement is this large is
  // accepted even when the removed support has unmodelled stats. A 25%+
  // gain is too large to plausibly stem from a composer blind-spot alone.
  const OVERRIDE_DELTA_PCT = 25;
  for (let pass = 0; pass < passes; pass++) {
    const res = optimizeSupports(build, mainIdx, skill.id, { topK: 5, minDeltaPct: 1 });
    // Trustworthy improvements first: no composer-blind-spot warning.
    // Fall back to large-delta improvements that override the warning gate.
    const trustworthy =
      res.topImprovements.find(s => !s.warning) ??
      res.topImprovements.find(s => s.deltaPct >= OVERRIDE_DELTA_PCT);
    if (!trustworthy) break;
    const group = build.skillGroups[mainIdx];
    const newGems = group.gems.slice();
    newGems[trustworthy.slotIndex] = {
      ...newGems[trustworthy.slotIndex],
      skillId: trustworthy.added.id,
      nameSpec: trustworthy.added.name,
      gemId: null,
      variantId: null,
    };
    build.skillGroups[mainIdx] = { ...group, gems: newGems };
    notes.push(`pass ${pass + 1}: swap slot ${trustworthy.slotIndex} "${trustworthy.removed.name}" → "${trustworthy.added.name}" (+${trustworthy.deltaPct.toFixed(1)}%)`);
  }

  // Step 6 — compose + validate. For spell skills, score both 'direct' and
  // 'cast_on_crit' trigger modes and pick the higher. Trigger mode is the
  // ONLY way Witch/Sorceress top-tier builds reach their headline DPS in
  // real PoE2 (Gaobin 180M Comet via Spark+CoC).
  const isSpell = skill.skillTypes.includes('Spell') && !skill.skillTypes.includes('Attack');
  let dps = 0;
  let triggerMode: 'direct' | 'cast_on_crit' = 'direct';
  try {
    const directDps = composeDamage({ build, skillGroupIndex: mainIdx, skillId: skill.id, triggerMode: 'direct' }).dps;
    if (isSpell) {
      const triggerDps = composeDamage({ build, skillGroupIndex: mainIdx, skillId: skill.id, triggerMode: 'cast_on_crit' }).dps;
      if (triggerDps > directDps) {
        dps = triggerDps;
        triggerMode = 'cast_on_crit';
        notes.push(`trigger mode selected: cast_on_crit (${triggerDps.toFixed(0)} > direct ${directDps.toFixed(0)})`);
      } else {
        dps = directDps;
      }
    } else {
      dps = directDps;
    }
  } catch (e) {
    notes.push(`compose error: ${(e as Error).message}`);
    return null;
  }
  const validation = validateBuild(build);

  return {
    skillId: skill.id,
    skillName: skill.name,
    weaponBase: bestWeapon.item.base ?? '',
    weaponRarity: bestWeapon.rarity,
    weaponUniqueName: bestWeapon.uniqueName,
    weaponModIds: bestWeapon.modIds,
    triggerMode,
    characterLevel: charLevel,
    gemLevel,
    passivePoints,
    itemLevel,
    build,
    dps,
    validation,
    notes,
  };
}

export interface GenerateTopOptions {
  itemLevel?: number;
  characterLevel?: number;
  gemLevel?: number;
  passivePoints?: number;
  ascendancy?: string;
}

/**
 * Candidate-skill filter per archetype. Decoupled from class so any class
 * with the same archetype shares the filter (e.g. Huntress + Ranger both
 * use 'bow-attack').
 */
type ArchetypeFilter = (cand: ReturnType<typeof candidateSkills>[number]) => boolean;
const ARCHETYPE_FILTER: Record<ClassProfile['archetype'], { profile?: 'attack' | 'spell'; filter: ArchetypeFilter; requireTag?: string }> = {
  'bow-attack': {
    profile: 'attack',
    requireTag: 'Bow',
    filter: () => true,
  },
  'crossbow-attack': {
    profile: 'attack',
    filter: c => c.weaponTypes.some(t => t === 'Crossbow') ||
                 c.skillTypes.includes('Crossbow'),
  },
  'mace-attack': {
    profile: 'attack',
    filter: c =>
      (c.skillTypes.includes('Melee') || c.skillTypes.includes('Slam')) &&
      c.weaponTypes.some(t => t === 'One Hand Mace' || t === 'Two Hand Mace'),
  },
  'staff-attack': {
    profile: 'attack',
    filter: c =>
      (c.skillTypes.includes('Melee') || c.skillTypes.includes('Slam')) &&
      c.weaponTypes.some(t => t === 'Quarterstaff' || t === 'Staff'),
  },
  spell: {
    profile: 'spell',
    filter: c =>
      c.skillTypes.includes('Spell') &&
      !c.skillTypes.includes('Attack') &&
      (c.weaponTypes.length === 0 ||
        c.weaponTypes.some(t => ['Wand', 'Staff', 'Sceptre'].includes(t))),
  },
  'shapeshift-totem': {
    // No `profile` — Shapeshift / SummonsTotem skills don't classify as
    // 'spell' or 'attack' in profileOf, so we rely entirely on the filter.
    filter: c =>
      c.skillTypes.includes('Shapeshift') ||
      c.skillTypes.includes('SummonsTotem'),
  },
};

/**
 * Generate the top-N highest-DPS builds for any class. The archetype
 * (and thus the candidate-skill filter) is derived from CLASS_PROFILE.
 */
export function generateTopBuildsForClass(
  className: string,
  topN = 3,
  options: GenerateTopOptions = {},
): GeneratedBuild[] {
  const profile = CLASS_PROFILE[className];
  if (!profile) throw new Error(`Unknown class: ${className}. Add to CLASS_PROFILE.`);
  const archetypeCfg = ARCHETYPE_FILTER[profile.archetype];
  const candidates = candidateSkills(className, {
    profile: archetypeCfg.profile,
    requireExactTag: archetypeCfg.requireTag,
  }).filter(archetypeCfg.filter);

  const generated: GeneratedBuild[] = [];
  for (const cand of candidates) {
    try {
      const b = generateBuildForSkill(className, cand.id, options);
      if (b && b.dps > 0) generated.push(b);
    } catch { /* non-fatal; skip the skill */ }
  }
  generated.sort((a, b) => b.dps - a.dps);
  return generated.slice(0, topN);
}

// Thin per-class wrappers — kept for test back-compat. New callers should
// use generateTopBuildsForClass directly.
export const generateTopBowAttackBuildsForHuntress = (topN = 3, o: GenerateTopOptions = {}) => generateTopBuildsForClass('Huntress', topN, o);
export const generateTopSpellBuildsForWitch        = (topN = 3, o: GenerateTopOptions = {}) => generateTopBuildsForClass('Witch', topN, o);
export const generateTopSpellBuildsForSorceress    = (topN = 3, o: GenerateTopOptions = {}) => generateTopBuildsForClass('Sorceress', topN, o);
export const generateTopMeleeBuildsForWarrior      = (topN = 3, o: GenerateTopOptions = {}) => generateTopBuildsForClass('Warrior', topN, o);
